### ISSUE TITLE
dist files for those of us who don't want to use node?

### ISSUE THREAD

**Issue by rcarmo** [goblindegook/littlefoot#1]
It would be nice to have the finished script available for downloading directly.

**Comment by bdesham** [comment]
I found littlefoot from [this comment in the Bigfoot issue tracker](https://github.com/lemonmade/bigfoot/issues/33#issuecomment-217519620), where it was advertised as not needing jQuery. But it seems that littlefoot requires some kind of module loader, along with babel-runtime, lodash, and several other libraries. Is that correct?

**Comment by goblindegook** [comment]
It only supports bundlers like Browserify, Webpack or Rollup for now, but I'll create a standalone version as soon as I lock down the API and move this out of alpha (shouldn't be long).

While I didn't want to use jQuery, I also didn't want to reinvent the wheel, so I'm relying on a couple of tiny dependencies for IE9 support, as well as a few Lodash functions and Babel polyfills for objects and arrays. The Lodash and Babel Runtime libraries are large-ish, but only the submodules I actually use are included, which is virtually the same as having manually written those functions into the library. (It's better in fact, because if you already use those modules elsewhere in your code, they're not duplicated.)

**Comment by goblindegook** [comment]
Trying out the npmcdn service, let me know if these scratch your itch:

* https://npmcdn.com/littlefoot@1.0.0-alpha.14/dist/littlefoot.min.js (41.3 KB, 12.3 KB gzipped)
* https://npmcdn.com/littlefoot@1.0.0-alpha.14/dist/littlefoot.css (5.8 KB, 1.9 KB gzipped)

The littlefoot script above is a UMD module supporting AMD and CommonJS imports, as well as a standalone version stored in the `window` object.

Please note that because of the way Babel transpiles ECMAScript 2015 modules, the create function is provided inside an object, so use `littlefoot.default({settings})` instead of simply `littlefoot({settings})`.

**Comment by bdesham** [comment]
That’s just the kind of packaging I’m looking for, thanks!
