### ISSUE TITLE
Sporadic formatting issues (rendered text too narrow)

### ISSUE THREAD

**Issue by kodster28** [goblindegook/littlefoot#1702]
Occasionally (very difficult to reproduce), we've noticed the footnote content rendering very narrowly (in a way that doesn't quite match the container).

<img width="1146" alt="Screenshot 2023-09-14 at 11 12 30" src="https://github.com/goblindegook/littlefoot/assets/26727299/db559bd0-972e-4ef2-a117-32327fbc9717">

**Comment by goblindegook** [comment]
Interesting, thanks for reporting this. Are you using the pre-release versions? Which browsers have you found the issue on?

**Comment by kodster28** [comment]
Primarily Chrome.

Not using any pre-release versions. Was using `4.0.0-9`, but recently upgraded to `4.0.0-10`.

**Comment by goblindegook** [comment]
Released `4.0.0-11` with some changes that will hopefully address the issue. Please let me know if you continue to notice it.

**Comment by kodster28** [comment]
Absolutely will do, thanks!!

**Comment by kevin1** [comment]
I guess this is probably the culprit: https://github.com/goblindegook/littlefoot/blob/0ca530efabf396c1e4c384fb7d52d59e1cb02468/src/dom/footnote.ts#L99

**Comment by kevin1** [comment]
I am able to reproduce the issue with these steps:

1. Reload the page
2. Resize the browser window before any footnotes have been opened
3. Open a footnote

Resizing the page causes this to run: https://github.com/goblindegook/littlefoot/blob/d709002a9b9b98cd6997c1f9f42aae0244a7375e/src/dom/footnote.ts#L96-L101

The code computes a very small `max-width` value because `content.offsetWidth` is zero when the footnote is not mounted, which is always true on first load. 

This should be gated by `isMounted`, which is checking for `popover.parentElement`:

https://github.com/goblindegook/littlefoot/blob/d709002a9b9b98cd6997c1f9f42aae0244a7375e/src/dom/footnote.ts#L25

Because of the way elements are created during littlefoot setup, `popover.parentElement` is always an empty `div` on first load:
https://github.com/goblindegook/littlefoot/blob/d709002a9b9b98cd6997c1f9f42aae0244a7375e/src/dom/document.ts#L48-L51

**Comment by goblindegook** [comment]
Thanks for investigating the issue!
